<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
<div class="row">
<?php foreach ($posts as $post): ?>
    <div class="col-sm-6" style="margin-bottom:30px;">
        <div class="row">
            <div class="col-lg-5">
                <div class="box-img">
                    <?php echo '<img alt="blog" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getImage().'" />'; ?>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="postWrapper">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                <h3><?php echo $post->getCreatedTime(); ?></h3>
            </div>
            <div class="postContent"><?php echo substr($post->getPostContent(),0,100); ?></div>
    
            <?php echo $this->getBookmarkHtml($post) ?>
            <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                        <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></div>
        </div>
            </div>
        </div>
        
    </div>
<?php endforeach; ?>
</div>
<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>