<?php
	if(!$this->getConfig('enabled')) return;
	$_productCollection=$this->getProductCollection();
	$_helper = $this->helper('catalog/output');
	$helpLabels = $this->helper('themevast/labels');
	$helpTimer = $this->helper('timer'); $num = 1;
?>
<?php
	// getConfig
	$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
	$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
	$price   		= $this->getShowPrice()?$this->getShowPrice():$this->getConfig('price');
	$cart    		= $this->getShowButton()?$this->getShowButton():$this->getConfig('cart');
	$compare  		= $this->getShowButton()?$this->getShowButton():$this->getConfig('compare');
	$wishlist  		= $this->getShowButton()?$this->getShowButton():$this->getConfig('wishlist');
	$review  		= $this->getShowReview()?$this->getShowReview():$this->getConfig('review');
	$slide  		= $this->getEnableSlide()?$this->getEnableSlide():$this->getConfig('slide');
	if($slide){
		$rows 			= $this->getRows()?$this->getRows():$this->getConfig('rows');
	}else{
		$rows 			= 1;	
	}
	$random         = $this->generateRandomString();
	$limit 			= $this->getLimit()?$this->getLimit():'';
?>
<div class="dailydeals">
	<?php echo $this->getConfig('title') ? '<div class="bx-title featured-title"><h2>'  .$this->__('Daily Deal!'). '</h2></div>' : '';
	if(!$_productCollection->count()): ?> 
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
	<div class="desciption"><?php echo $this->getConfig('description'); ?></div>
	<div class="products-grid <?php if(!$slide): ?>row<?php endif; ?>">
    	<?php $_collectionSize = $_productCollection->count() ?>
    	<?php $_columnCount = $this->getColumnCount(); ?>
    	<?php $j=0; $time = $this->getConfig('playDelay') ? $this->getConfig('playDelay') : 0; ?>
    	<?php $i=0;$k=0; foreach ($_productCollection as $_product): ?>
		<?php $t = $j*$time; $t .='ms'; $j++; ?>
		<?php if ($i++%$rows==0): ?>
			<div class="<?php if(!$slide): ?>item col-md-4 col-sm-6 col-sms-6 col-smb-12 <?php endif; ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
		<?php endif ?>
			<div class="item-inner">
				<div class="box-images">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					</a>
					<span class="time_lable">&nbsp;</span>
					
				</div>
				<div class="product-shop">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						
						<?php $sub_name = $_product->getSubName(); ?>
						<?php if($sub_name): ?>
							<div class="sub-name">
								<?php echo $sub_name; ?>
							</div>
						<?php endif; ?>
						<?php if($review): ?>
							<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php if($price): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>

						
				</div>
				<?php echo $helpTimer->getTimer($_product, $num); $num++;//Product Timer ?>
				
                    <?php //echo $helpLabels->getLabels($_product); //Product labels ?>
                
            </div>
		<?php if ($i%$rows==0 || $i%$_productCollection->count()==0): ?>
			</div>
		<?php endif ?>
		<?php if(++$k == $limit) break; ?>
		<?php endforeach ?>
	</div>
	<?php endif ?>
	<?php if($slide ==1) : ?>
		<script type="text/javascript">
			jQuery(document).ready(function($){
			(function(selector){
				var $content = $(selector);
				var $slider  = $('.products-grid', $content);
				var slider 	 = $slider.owlCarousel({
						<?php if($this->getConfig('autoPlay') == 0): ?>
						autoplay: false, 
						<?php else: ?>
						autoplay: true,
						<?php endif; ?>
						autoplaySpeed: <?php echo $this->getSlideSpeed()?$this->getSlideSpeed():$this->getConfig('slideSpeed'); ?>, 
						nav: <?php echo ($this->getConfig('navigation') == 1? "true": "false"); ?>, 
						dots: <?php echo ($this->getConfig('pagination') == 1? "true": "false"); ?>, 
						loop: false,
						autoplayHoverPause: <?php echo ($this->getConfig('stopOnHover') == 1? "true": "false"); ?>,
						responsive: {<?php echo ($this->getResponsive()?$this->getResponsive():$this->getConfig('responsive')) ?>},
						margin: <?php echo $this->getConfig('margin') ?>,
						//padding: 10 
					})

			})(".dailydeals");
		});
		</script>
	<?php endif; ?>
</div>





